config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "top#index"
  get "balance_confirm" => "balance_confirm#index"
  post "balance_confirm/show(/:name)" => "balance_confirm#show"
  get "balance_confirm/show(/:name)" => "balance_confirm#show"
  post "blance_confirm/show_year(/:name)" => "balance_confirm#show_year"
  get "blance_confirm/show_year(/:name)" => "balance_confirm#show_year"
  
  resources :incomes 
  resources :fixedcosts
  resources :variablecosts
end

app/models/variablecost.rb
class Variablecost < ApplicationRecord
  belongs_to :user
  INTEGER_LONG_REQUIRED  = { numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 9999999 } }
  validates :value,  INTEGER_LONG_REQUIRED
  with_options presence: true do
    validates :year_month, :name, :value, :user_id
  end
end

app/controllers/variablecosts_controller.rb
class VariablecostsController < ApplicationController
  before_action :set_variablecost, only: [:edit, :show, :update, :destroy]
  before_action :confirmation

  def index
    variablecosts = Variablecost.where(user_id: current_user.id)
    @variablecosts = variablecosts.order(created_at: :asc)
  end

  def new
    @variablecost = Variablecost.new
  end

  def create
    @variablecost = Variablecost.new(variablecost_params)
    if @variablecost.save
      redirect_to variablecosts_path, notice: "収入を登録しました"
    else
      render "new"
    end
  end

  def edit
  end

  def show
  end

  def update
    if @variablecost.update(variablecost_params)
      redirect_to variablecosts_path, notice: "収入を登録しました"
    else
      render 'edit'
   end
  end

  def destroy
    @variablecost.destroy
    redirect_to variablecosts_path, notice: "収入を削除しました"
  end

  private
  def variablecost_params
    params.require(:variablecost).permit(:name, :year_month, :value, :description).merge(user_id: current_user.id)
  end

  def set_variablecost
    @variablecost = Variablecost.find(params[:id])
  end

  def confirmation
    unless user_signed_in?
      redirect_to root_path
    end
  end

end

app/helpers/variablecosts_helper.rb
module VariablecostsHelper
end

app/views/variablecosts/edit.html.erb
<div id="wrapper">
  <%= render "shared/header" %>
    <div id="contents">
      <h2>変動費編集</h2>
      <%= form_with model: @variablecost, local: true do |f| %>
        <%= render 'shared/error_messages', model: f.object %>
      <table border="1">
        <tr>
          <th>登録年月</th>
          <th>名称</th>
          <th>金額</th>
          <th>備考</th>
        </tr>
        <tr>  
          <td>
            <%= f.date_select :year_month,
            start_year: 2010, end_year: Time.current.year,
            use_month_numbers: true, discard_day: true, default: @year_month%>
          </td>
          <td><%= f.text_field :name %></td>
          <td><%= f.text_field :value, size: 8 %></td>
          <td><%= f.text_field :description, size: 20 %></td>
       </tr>
      </table>
      <br>
        <div><%= f.submit "保存する" %></div> 
        <% end %>
    </div>
    <br>
    <div id="sidebar">
    <p class="side-title">収支設定</p>
      <ul class="localnavi">
        <li><%= link_to "収入設定", :incomes %></li>
        <li><%= link_to "固定費設定", :fixedcosts %></li>
        <li><%= link_to "変動費設定", :variablecosts %></li>
      </ul>
        <p class="side-title">収支確認</p>
      <ul class="localnavi">
        <li><%= link_to "収支確認画面", balance_confirm_path %></li>
      </ul>
      <p><%= link_to '戻る', variablecosts_path %></p>
  </div>
  <p id="cds">Yoshiaki</p>
<%= render "shared/hooter" %>
</div>

app/views/variablecosts/index.html.erb
<div id="wrapper">
  <%= render "shared/header" %>
    <div id="contents">
      <h2><%= link_to "変動費の新規登録", new_variablecost_path %></h2>
        <br>
      <h3>変動費科目 データ一覧</h3>
      <% if @variablecosts.present? %>
      <table border="1">
        <tr>
          <th>登録年月</th>
          <th>名称</th>
          <th>金額</th>
          <th>備考</th>
          <th>操作</th>
        </tr>
        <% @variablecosts.each do |variablecost| %>
        <tr>
        <td><%= variablecost.year_month.strftime('%Y年%m月') %></td>
          <td><%= variablecost.name %></td>
          <td><%= variablecost.value.to_s(:delimited) %> 円</td>
          <td><%= variablecost.description %></td>
          <td>
          <%= link_to "編集", [:edit, variablecost] %> |
          <%= link_to "削除", variablecost, method: :delete,data: { confirm: "本当に削除しますか？"} %>
          </td>
        </tr>
        <% end %>
      </table>
      <% else %>
        <p>登録されているデータがありません。</p>
      <% end %>
          </div>
          <br>
    <div id="sidebar">
    <p class="side-title">収支設定</p>
      <ul class="localnavi">
        <li><%= link_to "収入設定", :incomes %></li>
        <li><%= link_to "固定費設定", :fixedcosts %></li>
        <li><%= link_to "変動費設定", :variablecosts %></li>
      </ul>
        <p class="side-title">収支確認</p>
      <ul class="localnavi">
        <li><%= link_to "収支確認画面", balance_confirm_path %></li>
      </ul>
  </div>
  <p id="cds">Yoshiaki</p>
<%= render "shared/hooter" %>
</div>

app/views/variablecosts/new.html.erb
<div id="wrapper">
  <%= render "shared/header" %>
    <div id="contents">
      <h2>変動費登録</h2>
      <%= form_with model: @variablecost, local: true do |f| %>
        <%= render 'shared/error_messages', model: f.object %>
      <table border="1">
        <tr>
          <th>登録年月</th>
          <th>名称</th>
          <th>金額</th>
          <th>備考</th>
        </tr>
        <tr>  
          <td>
            <%= f.date_select :year_month,
            start_year: 2010, end_year: Time.current.year,
            use_month_numbers: true, discard_day: true, default: @year_month%>
          </td>
          <td><%= f.text_field :name, size: 15 %></td>
          <td><%= f.text_field :value, size: 8 %></td>
          <td><%= f.text_field :description, size: 15 %></td>
       </tr>
      </table>
      <br>
        <div><%= f.submit "保存する" %></div> 
        <% end %>
    </div>
    <br>
    <div id="sidebar">
    <p class="side-title">収支設定</p>
      <ul class="localnavi">
        <li><%= link_to "収入設定", :incomes %></li>
        <li><%= link_to "固定費設定", :fixedcosts %></li>
        <li><%= link_to "変動費設定", :variablecosts %></li>
      </ul>
        <p class="side-title">収支確認</p>
      <ul class="localnavi">
        <li><%= link_to "収支確認画面", balance_confirm_path %></li>
      </ul>
      <p><%= link_to '戻る', variablecosts_path %></p>
  </div>
  <p id="cds">Yoshiaki</p>
<%= render "shared/hooter" %>
</div>